export type Product={id:string;name:string;price?:number;category?:string;type:'product'|'service';description?:string;image:string;featured?:boolean;bestseller?:boolean;stock?:number;active?:boolean};
export type Category={id:string;name:string;slug?:string;type:'product'|'service';description?:string;image?:string;active?:boolean;createdAt?:string;};
export type Order={
	id:string;
	items:{id?:string;name?:string;category?:string;price?:number;qty?:number;quantity?:number;image?:string}[];
	subtotal:number;
	shipping:number;
	tax:number;
	total:number;
	taxRate?:number;
	shippingFee?:number;
	discountAmount?:number;
	paymentMethod:string;
	paymentReference?:string;
	status:string;
	createdAt:string;
	customer?:{name:string;phone:string;address:string};
	customerEmail?:string;
	customerName?:string;
	customerPhone?:string;
	customerAddress?:string;
	shippingAddress?:string;
	address?:string;
	deliveryDays?: string;
    deliveryDaysCount?: number;
    estimatedDeliveryDate?: string;  
};
export type Session={id:string;userId:string;email:string;loginAt:string;userAgent:string};
