export type Product={id:string;name:string;price:number;category:string;type:'product'|'service';description:string;image:string;featured?:boolean;bestseller?:boolean;stock:number};
export type Order={
	id:string;
	items:{id:string;name:string;price:number;qty:number}[];
	subtotal:number;
	shipping:number;
	tax:number;
	total:number;
	taxRate?:number;
	shippingFee?:number;
	discountAmount?:number;
	paymentMethod:string;
	paymentReference?:string;
	status:string;
	createdAt:string;
	customer?:{name:string;phone:string;address:string};
	customerEmail?:string;
	customerName?:string;
	customerPhone?:string;
	customerAddress?:string;
};
export type Session={id:string;userId:string;email:string;loginAt:string;userAgent:string};
